version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:2707"
    volumes:
      - mongo_data:/data/db

  usuarios:
    build: ./services/usuarios
    container_name: usuarios
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/usuarios_db
    ports:
      - "4001:4001"
    depends_on:
      - mongodb

  productos:
    build: ./services/productos
    container_name: productos
    restart: always
    env_file:
      - ./services/productos/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/productos_db
    ports:
      - "4002:4002"
    depends_on:
      - mongodb

volumes:
  mongo_data:
